# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arjun's blog
email: arjun.rajeev@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Arjun is a seasoned professional with over 8 years of experience in 
  software test automation. He is committed towards continuous delivery,
   implementing industry best practices and passionate about designing 
  test automation frameworks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arjunrajeev.co.in" # the base hostname & protocol for your site
sass:
  sass_dir: _sass
github_username:  arjun-rajeev
disqus: arjun_rajeev
# Build settings
markdown: kramdown
